### ISSUE TITLE
"Error: package or namespace load failed for 'scpdata'" when installing dev version

### ISSUE THREAD

**Issue by Cajun-data** [UCLouvain-CBIO/scpdata#14]
Hi - I am running into an issue installing using:
remotes::install_github("UCLouvain-CBIO/scpdata",
                        force = T)
                        
 I receive the following error:
 ** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'scpdata':
 .onLoad failed in loadNamespace() for 'scpdata', details:
  call: FUN(X[[i]], ...)
  error: 'leduc2022_pSCoPE' not found in ExperimentHub
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/R_Library/scpdata'
* restoring previous 'C:/R_Library/scpdata'

**Comment by lgatto** [comment]
My guess is that you are running the current release version of Bioconductor, i.e 3.17, but `leduc2022_pSCoPE` was added as part of the devel version (3.18). You can check this with

```
> BiocManager::version()
[1] ‘3.17’
```

that reproduces your issue, and 

```
> BiocManager::version()
[1] ‘3.18’
```

that succeeds.

This is also confirmed by the package's [NEWS](https://github.com/UCLouvain-CBIO/scpdata/blob/master/NEWS.md) file, that indicates that `leduc2022_pSCoPE` (and other) data have been added to the devel release. 

See [Using the ‘Devel’ Version of Bioconductor](https://contributions.bioconductor.org/use-devel.html) for details on using Bioc *devel*.

The take-home message here is to always install Bioconductor package with `BiocManager::install()`.
