### ISSUE TITLE
Publish `scpdata` to Bioconductor

### ISSUE THREAD

**Issue by cvanderaa** [UCLouvain-CBIO/scpdata#6]
The package is ready for submission to Bioconductor. The datasets are in `ExperiementHub` and can effectively be retrieved. 

The package **passes all CRAN checks**. 

The package passes the BiocChecks with **3 notes**: 
- 16 lines are >80chars: unavoidable (mainly URL links and code chunk headers)
- Cannot determine whether maintainer is subscribed to the bioc-devel mailing list: this is a bug, I am subscribed
- No unit test: should I include some? What should I test for? 

@lgatto could you give the package a review before I submit it to Bioconductor?

**Comment by cvanderaa** [comment]
The latest changes are now live on ExperimentHub. If you @lgatto agree, I can proceed and submit the package to Bioconductor!

**Comment by lgatto** [comment]
- Re unit tests, could you check whether there are any in other similar data packages.

Otherwise, yes, please go ahead and submit.

**Comment by cvanderaa** [comment]
I added a few unit tests taken from the `curatedTCGAData` package.

**Comment by cvanderaa** [comment]
Submitted, see [here](https://github.com/Bioconductor/Contributions/issues/1839) !
