### ISSUE TITLE
Bug in README

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/scpdata#9]
Bug in the README file. This code chunk is wrong:

```r
scp <- datasets[["EH3899"]]
```

given that `datasets` isn't defined.

**Comment by lgatto** [comment]
Also, as far as I can see, there's no `"EH3899"` (not any of the `scpdata` experiments) record (yet). Are these the record identifiers that have been reserved for the `scpdata` datasets once it is accepted?

**Comment by cvanderaa** [comment]
Good catch! I overlooked the `R` code and the code chunks were not up-to-date. I improved the `README`, with additional code and text. The `"EH3899"` is the `ExperimentHub` ID, not the data set title. I added some text to hopefully make this clearer.
